//rgba(0, 103, 130)
export const  enum $color {
  scrim = '#000000',
  primary = '#006687',
  onPrimary = '#ffffff',
  primaryContainer = '#c1e8ff',
  onPrimaryContainer = '#001e2b',
  secondary = '#4d616c',
  onSecondary = '#ffffff',
  secondaryContainer = '#d0e6f3',
  onSecondaryContainer = '#091e27',
  tertiary = '#5f5a7d',
  onTertiary = '#ffffff',
  tertiaryContainer = '#e5deff',
  onTertiaryContainer = '#1b1736',
  error = '#ba1a1a',
  onError = '#ffffff',
  errorContainer = '#ffdad6',
  onErrorContainer = '#410002',
  background = '#fbfcfe',
  onBackground = '#191c1e',
  outline = '#71787d',
  outlineVariant = '#c0c7cd',
  surface = '#fbfcfe',
  onSurface = '#191c1e',
  surfaceVariant = '#dce3e9',
  onSurfaceVariant = '#40484c',
  inverseSurface = '#2e3133',
  inverseOnSurface = '#f0f1f3',
  inversePrimary = '#73d1ff',
  surfaceContainerLowest = '#ffffff',
  surfaceContainerLow = '#f3f4f6',
  surfaceContainer = '#edeef0',
  surfaceContainerHigh = '#e7e8ea',
  surfaceContainerHighest = '#e1e2e5',
  darkScrim = '#000000',
  darkPrimary = '#73d1ff',
  darkOnPrimary = '#003548',
  darkPrimaryContainer = '#004d67',
  darkOnPrimaryContainer = '#c1e8ff',
  darkSecondary = '#b5cad7',
  darkOnSecondary = '#1f333d',
  darkSecondaryContainer = '#364954',
  darkOnSecondaryContainer = '#d0e6f3',
  darkTertiary = '#c8c2ea',
  darkOnTertiary = '#302c4c',
  darkTertiaryContainer = '#474364',
  darkOnTertiaryContainer = '#e5deff',
  darkError = '#ffb4ab',
  darkOnError = '#690005',
  darkErrorContainer = '#93000a',
  darkOnErrorContainer = '#ffb4ab',
  darkBackground = '#191c1e',
  darkOnBackground = '#e1e2e5',
  darkOutline = '#8a9297',
  darkOutlineVariant = '#40484c',
  darkSurface = '#191c1e',
  darkOnSurface = ' #e1e2e5',
  darkSurfaceVariant = '#40484c',
  darkOnSurfaceVariant = '#c0c7cd',
  darkInverseSurface = '#e1e2e5',
  darkInverseOnSurface = '#2e3133',
  darkInversePrimary = '#006687',
  darkSurfaceContainerLowest = '#0c0f10',
  darkSurfaceContainerLow = '#191c1e',
  darkSurfaceContainer = '#1d2022',
  darkSurfaceContainerHigh = '#282a2c',
  darkSurfaceContainerHighest = '#323537',
  success = '#006d3d',
  onSuccess = '#ffffff',
  successContainer = '#92f8b4',
  onSuccessContainer = '#00210f',
  darkSuccess = '#76db9a',
  darkOnSuccess = '#00391d',
  darkSuccessContainer = '#00522c',
  darkOnSuccessContainer = '#92f8b4',
  warning = '#6f5d00',
  onWarning = '#ffffff',
  warningContainer = '#ffe169',
  onWarningContainer = '#221b00',
  darkWarning = '#e2c54b',
  darkOnWarning = '#3a3000',
  darkWarningContainer = '#544600',
  darkOnWarningContainer = '#ffe169',
}

export const enum color {
  scrim = `var(--s-color-scrim, ${$color.scrim})`,
  primary = `var(--s-color-primary, ${$color.primary})`,
  onPrimary = `var(--s-color-on-primary, ${$color.onPrimary})`,
  primaryContainer = `var(--s-color-primary-container, ${$color.primaryContainer})`,
  onPrimaryContainer = `var(--s-color-on-primary-container, ${$color.onPrimaryContainer})`,
  secondary = `var(--s-color-secondary, ${$color.secondary})`,
  onSecondary = `var(--s-color-on-secondary, ${$color.onSecondary})`,
  secondaryContainer = `var(--s-color-secondary-container, ${$color.secondaryContainer})`,
  onSecondaryContainer = `var(--s-color-on-secondary-container, ${$color.onSecondaryContainer})`,
  tertiary = `var(--s-color-tertiary, ${$color.tertiary})`,
  onTertiary = `var(--s-color-on-tertiary, ${$color.onTertiary})`,
  tertiaryContainer = `var(--s-color-tertiary-container, ${$color.tertiaryContainer})`,
  onTertiaryContainer = `var(--s-color-on-tertiary-container, ${$color.onTertiaryContainer})`,
  error = `var(--s-color-error, ${$color.error})`,
  onError = `var(--s-color-on-error, ${$color.onError})`,
  errorContainer = `var(--s-color-error-container, ${$color.errorContainer})`,
  onErrorContainer = `var(--s-color-on-error-container, ${$color.onErrorContainer})`,
  background = `var(--s-color-background, ${$color.background})`,
  onBackground = `var(--s-color-on-background, ${$color.onBackground})`,
  outline = `var(--s-color-outline, ${$color.outline})`,
  outlineVariant = `var(--s-color-outline-variant, ${$color.outlineVariant})`,
  surface = `var(--s-color-surface, ${$color.surface})`,
  onSurface = `var(--s-color-on-surface, ${$color.onSurface})`,
  surfaceVariant = `var(--s-color-surface-variant, ${$color.surfaceVariant})`,
  onSurfaceVariant = `var(--s-color-on-surface-variant, ${$color.onSurfaceVariant})`,
  inverseSurface = `var(--s-color-inverse-surface, ${$color.inverseSurface})`,
  inverseOnSurface = `var(--s-color-inverse-on-surface, ${$color.inverseOnSurface})`,
  inversePrimary = `var(--s-color-inverse-primary, ${$color.inversePrimary})`,
  surfaceContainerLowest = `var(--s-color-surface-container-lowest, ${$color.surfaceContainerLowest})`,
  surfaceContainerLow = `var(--s-color-surface-container-low, ${$color.surfaceContainerLow})`,
  surfaceContainer = `var(--s-color-surface-container, ${$color.surfaceContainer})`,
  surfaceContainerHigh = `var(--s-color-surface-container-high, ${$color.surfaceContainerHigh})`,
  surfaceContainerHighest = `var(--s-color-surface-container-highest, ${$color.surfaceContainerHighest})`,
  darkScrim = `var(--s-color-dark-scrim, ${$color.darkScrim})`,
  darkPrimary = `var(--s-color-dark-primary, ${$color.darkPrimary})`,
  darkOnPrimary = `var(--s-color-dark-on-primary, ${$color.darkOnPrimary})`,
  darkPrimaryContainer = `var(--s-color-dark-primary-container, ${$color.darkPrimaryContainer})`,
  darkOnPrimaryContainer = `var(--s-color-dark-on-primary-container, ${$color.darkOnPrimaryContainer})`,
  darkSecondary = `var(--s-color-dark-secondary, ${$color.darkSecondary})`,
  darkOnSecondary = `var(--s-color-dark-on-secondary, ${$color.darkOnSecondary})`,
  darkSecondaryContainer = `var(--s-color-dark-secondary-container, ${$color.darkSecondaryContainer})`,
  darkOnSecondaryContainer = `var(--s-color-dark-on-secondary-container, ${$color.darkOnSecondaryContainer})`,
  darkTertiary = `var(--s-color-dark-tertiary, ${$color.darkTertiary})`,
  darkOnTertiary = `var(--s-color-dark-on-tertiary, ${$color.darkOnTertiary})`,
  darkTertiaryContainer = `var(--s-color-dark-tertiary-container, ${$color.darkTertiaryContainer})`,
  darkOnTertiaryContainer = `var(--s-color-dark-on-tertiary-container, ${$color.darkOnTertiaryContainer})`,
  darkError = `var(--s-color-dark-error, ${$color.darkError})`,
  darkOnError = `var(--s-color-dark-on-error, ${$color.darkOnError})`,
  darkErrorContainer = `var(--s-color-dark-error-container, ${$color.darkErrorContainer})`,
  darkOnErrorContainer = `var(--s-color-dark-on-error-container, ${$color.darkOnErrorContainer})`,
  darkBackground = `var(--s-color-dark-background, ${$color.darkBackground})`,
  darkOnBackground = `var(--s-color-dark-on-background, ${$color.darkOnBackground})`,
  darkOutline = `var(--s-color-dark-outline, ${$color.darkOutline})`,
  darkOutlineVariant = `var(--s-color-dark-outline-variant, ${$color.darkOutlineVariant})`,
  darkSurface = `var(--s-color-dark-surface, ${$color.darkSurface})`,
  darkOnSurface = `var(--s-color-dark-on-surface, ${$color.darkOnSurface})`,
  darkSurfaceVariant = `var(--s-color-dark-surface-variant, ${$color.darkSurfaceVariant})`,
  darkOnSurfaceVariant = `var(--s-color-dark-on-surface-variant, ${$color.darkOnSurfaceVariant})`,
  darkInverseSurface = `var(--s-color-dark-inverse-surface, ${$color.darkInverseSurface})`,
  darkInverseOnSurface = `var(--s-color-dark-inverse-on-surface, ${$color.darkInverseOnSurface})`,
  darkInversePrimary = `var(--s-color-dark-inverse-primary, ${$color.darkInversePrimary})`,
  darkSurfaceContainerLowest = `var(--s-color-dark-surface-container-lowest, ${$color.darkSurfaceContainerLowest})`,
  darkSurfaceContainerLow = `var(--s-color-dark-surface-container-low, ${$color.darkSurfaceContainerLow})`,
  darkSurfaceContainer = `var(--s-color-dark-surface-container, ${$color.darkSurfaceContainer})`,
  darkSurfaceContainerHigh = `var(--s-color-dark-surface-container-high, ${$color.darkSurfaceContainerHigh})`,
  darkSurfaceContainerHighest = `var(--s-color-dark-surface-container-highest, ${$color.darkSurfaceContainerHighest})`,
  success = `var(--s-color-success, ${$color.success})`,
  onSuccess = `var(--s-color-on-success, ${$color.onSuccess})`,
  successContainer = `var(--s-color-success-container, ${$color.successContainer})`,
  onSuccessContainer = `var(--s-color-on-success-container, ${$color.onSuccessContainer})`,
  darkSuccess = `var(--s-color-dark-success, ${$color.darkSuccess})`,
  darkOnSuccess = `var(--s-color-dark-on-success, ${$color.darkOnSuccess})`,
  darkSuccessContainer = `var(--s-color-dark-success-container, ${$color.darkSuccessContainer})`,
  darkOnSuccessContainer = `var(--s-color-dark-on-success-container, ${$color.darkOnSuccessContainer})`,
  warning = `var(--s-color-warning, ${$color.warning})`,
  onWarning = `var(--s-color-on-warning, ${$color.onWarning})`,
  warningContainer = `var(--s-color-warning-container, ${$color.warningContainer})`,
  onWarningContainer = `var(--s-color-on-warning-container, ${$color.onWarningContainer})`,
  darkWarning = `var(--s-color-dark-warning, ${$color.darkWarning})`,
  darkOnWarning = `var(--s-color-dark-on-warning, ${$color.darkOnWarning})`,
  darkWarningContainer = `var(--s-color-dark-warning-container, ${$color.darkWarningContainer})`,
  darkOnWarningContainer = `var(--s-color-dark-on-warning-container, ${$color.darkOnWarningContainer})`
}

export const enum $elevation {
  level1 = '0 3px 1px -2px rgba(0, 0, 0, .2), 0 2px 2px 0 rgba(0, 0, 0, .14), 0 1px 5px 0 rgba(0, 0, 0, .12)',
  level2 = '0 2px 4px -1px rgba(0, 0, 0, .2), 0 4px 5px 0 rgba(0, 0, 0, .14), 0 1px 10px 0 rgba(0, 0, 0, .12)',
  level3 = '0 5px 5px -3px rgba(0, 0, 0, .2), 0 8px 10px 1px rgba(0, 0, 0, .14), 0 3px 14px 2px rgba(0, 0, 0, .12)',
  level4 = '0 8px 10px -5px rgba(0, 0, 0, .2), 0 16px 24px 2px rgba(0, 0, 0, .14), 0 6px 30px 5px rgba(0, 0, 0, .12)',
  level5 = '0 10px 14px -6px rgba(0, 0, 0, .2), 0 22px 35px 3px rgba(0, 0, 0, .14), 0 8px 42px 7px rgba(0, 0, 0, .12)',
}

export const enum elevation {
  level1 = `var(--s-elevation-level1, ${$elevation.level1})`,
  level2 = `var(--s-elevation-level2, ${$elevation.level2})`,
  level3 = `var(--s-elevation-level3, ${$elevation.level3})`,
  level4 = `var(--s-elevation-level4, ${$elevation.level4})`,
  level5 = `var(--s-elevation-level5, ${$elevation.level5})`,
}

export namespace $motion {
  export const enum duration {
    short1 = '50ms',
    short2 = '100ms',
    short3 = '150ms',
    short4 = '200ms',
    medium1 = '250ms',
    medium2 = '300ms',
    medium3 = '350ms',
    medium4 = '400ms',
    long1 = '450ms',
    long2 = '500ms',
    long3 = '550ms',
    long4 = '600ms',
    extraLong1 = '700ms',
    extraLong2 = '800ms',
    extraLong3 = '900ms',
    extraLong4 = '1000ms',
  }
  export const enum easing {
    emphasized = 'cubic-bezier(0.2, 0, 0, 1.0)',
    emphasizedDecelerate = 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
    emphasizedAccelerate = 'cubic-bezier(0.3, 0, 0.8, 0.15)',
    standard = 'cubic-bezier(0.2, 0, 0, 1.0)',
    standardDecelerate = 'cubic-bezier(0, 0, 0, 1)',
    standardAccelerate = 'cubic-bezier(0.3, 0, 1, 1)'
  }
}

export namespace motion {
  export const enum duration {
    short1 = `var(--s-motion-duration-short1, ${$motion.duration.short1})`,
    short2 = `var(--s-motion-duration-short2, ${$motion.duration.short2})`,
    short3 = `var(--s-motion-duration-short3, ${$motion.duration.short3})`,
    short4 = `var(--s-motion-duration-short4, ${$motion.duration.short4})`,
    medium1 = `var(--s-motion-duration-medium1, ${$motion.duration.medium1})`,
    medium2 = `var(--s-motion-duration-medium2, ${$motion.duration.medium2})`,
    medium3 = `var(--s-motion-duration-medium3, ${$motion.duration.medium3})`,
    medium4 = `var(--s-motion-duration-medium4, ${$motion.duration.medium4})`,
    long1 = `var(--s-motion-duration-long1, ${$motion.duration.long1})`,
    long2 = `var(--s-motion-duration-long2, ${$motion.duration.long2})`,
    long3 = `var(--s-motion-duration-long3, ${$motion.duration.long3})`,
    long4 = `var(--s-motion-duration-long4, ${$motion.duration.long4})`,
    extraLong1 = `var(--s-motion-duration-extraLong1, ${$motion.duration.extraLong1})`,
    extraLong2 = `var(--s-motion-duration-extraLong2, ${$motion.duration.extraLong2})`,
    extraLong3 = `var(--s-motion-duration-extraLong3, ${$motion.duration.extraLong3})`,
    extraLong4 = `var(--s-motion-duration-extraLong4, ${$motion.duration.extraLong4})`,
  }
  export const enum easing {
    emphasized = `var(--s-motion-easing-emphasized, ${$motion.easing.emphasized})`,
    emphasizedDecelerate = `var(--s-motion-easing-emphasizedDecelerate, ${$motion.easing.emphasizedDecelerate})`,
    emphasizedAccelerate = `var(--s-motion-easing-emphasizedAccelerate, ${$motion.easing.emphasizedAccelerate})`,
    standard = `var(--s-motion-easing-standard, ${$motion.easing.standard})`,
    standardDecelerate = `var(--s-motion-easing-standardDecelerate, ${$motion.easing.standardDecelerate})`,
    standardAccelerate = `var(--s-motion-easing-standardAccelerate, ${$motion.easing.standardAccelerate})`,
  }
}