//#2c9aaf
export const enum $color {
  lightScrim = '#000000',
  lightPrimary = '#00658e',
  lightOnPrimary = '#ffffff',
  lightPrimaryContainer = '#c7e7ff',
  lightOnPrimaryContainer = '#004c6c',
  lightSecondary = '#4f616e',
  lightOnSecondary = '#ffffff',
  lightSecondaryContainer = '#d2e5f5',
  lightOnSecondaryContainer = '#374955',
  lightTertiary = '#62597c',
  lightOnTertiary = '#ffffff',
  lightTertiaryContainer = '#e8ddff',
  lightOnTertiaryContainer = '#4a4263',
  lightError = '#ba1a1a',
  lightOnError = '#ffffff',
  lightErrorContainer = '#ffdad6',
  lightOnErrorContainer = '#93000a',
  lightSurface = '#f9f9fc',
  lightOnSurface = '#191c1e',
  lightSurfaceVariant = '#dde3ea',
  lightOnSurfaceVariant = '#41484d',
  lightSurfaceContainerHighest = '#e2e2e5',
  lightSurfaceContainerHigh = '#e7e8eb',
  lightSurfaceContainer = '#edeef0',
  lightSurfaceContainerLow = '#f3f3f6',
  lightSurfaceContainerLowest = '#ffffff',
  lightInverseSurface = '#2e3133',
  lightInverseOnSurface = '#f0f1f3',
  lightInversePrimary = '#84cfff',
  lightBackground = '#f9f9fc',
  lightOnBackground = '#191c1e',
  lightOutline = '#71787e',
  lightOutlineVariant = '#c1c7ce',
  lightSuccess = '#006d3d',
  lightOnSuccess = '#ffffff',
  lightSuccessContainer = '#92f8b4',
  lightOnSuccessContainer = '#00210f',
  lightWarning = '#6f5d00',
  lightOnWarning = '#ffffff',
  lightWarningContainer = '#ffe169',
  lightOnWarningContainer = '#221b00',
  darkScrim = '#000000',
  darkPrimary = '#84cfff',
  darkOnPrimary = '#00344c',
  darkPrimaryContainer = '#004c6c',
  darkOnPrimaryContainer = '#c7e7ff',
  darkSecondary = '#b6c9d8',
  darkOnSecondary = '#21323e',
  darkSecondaryContainer = '#374955',
  darkOnSecondaryContainer = '#d2e5f5',
  darkTertiary = '#ccc0e9',
  darkOnTertiary = '#342b4b',
  darkTertiaryContainer = '#4a4263',
  darkOnTertiaryContainer = '#e8ddff',
  darkError = '#ffb4ab',
  darkOnError = '#690005',
  darkErrorContainer = '#93000a',
  darkOnErrorContainer = '#ffdad6',
  darkSurface = '#111416',
  darkOnSurface = '#e2e2e5',
  darkSurfaceVariant = '#41484d',
  darkOnSurfaceVariant = '#c1c7ce',
  darkSurfaceContainerHighest = '#333537',
  darkSurfaceContainerHigh = '#282a2c',
  darkSurfaceContainer = '#1d2022',
  darkSurfaceContainerLow = '#191c1e',
  darkSurfaceContainerLowest = '#0c0e10',
  darkInverseSurface = '#e2e2e5',
  darkInverseOnSurface = '#2e3133',
  darkInversePrimary = '#00658e',
  darkBackground = '#111416',
  darkOnBackground = '#e2e2e5',
  darkOutline = '#8b9198',
  darkOutlineVariant = '#41484d',
  darkSuccess = '#76db9a',
  darkOnSuccess = '#00391d',
  darkSuccessContainer = '#00522c',
  darkOnSuccessContainer = '#92f8b4',
  darkWarning = '#e2c54b',
  darkOnWarning = '#3a3000',
  darkWarningContainer = '#544600',
  darkOnWarningContainer = '#ffe169',
}

export const enum color {
  scrim = `var(--s-color-scrim, ${$color.lightScrim})`,
  primary = `var(--s-color-primary, ${$color.lightPrimary})`,
  onPrimary = `var(--s-color-on-primary, ${$color.lightOnPrimary})`,
  primaryContainer = `var(--s-color-primary-container, ${$color.lightPrimaryContainer})`,
  onPrimaryContainer = `var(--s-color-on-primary-container, ${$color.lightOnPrimaryContainer})`,
  secondary = `var(--s-color-secondary, ${$color.lightSecondary})`,
  onSecondary = `var(--s-color-on-secondary, ${$color.lightOnSecondary})`,
  secondaryContainer = `var(--s-color-secondary-container, ${$color.lightSecondaryContainer})`,
  onSecondaryContainer = `var(--s-color-on-secondary-container, ${$color.lightOnSecondaryContainer})`,
  tertiary = `var(--s-color-tertiary, ${$color.lightTertiary})`,
  onTertiary = `var(--s-color-on-tertiary, ${$color.lightOnTertiary})`,
  tertiaryContainer = `var(--s-color-tertiary-container, ${$color.lightTertiaryContainer})`,
  onTertiaryContainer = `var(--s-color-on-tertiary-container, ${$color.lightOnTertiaryContainer})`,
  error = `var(--s-color-error, ${$color.lightError})`,
  onError = `var(--s-color-on-error, ${$color.lightOnError})`,
  errorContainer = `var(--s-color-error-container, ${$color.lightErrorContainer})`,
  onErrorContainer = `var(--s-color-on-error-container, ${$color.lightOnErrorContainer})`,
  background = `var(--s-color-background, ${$color.lightBackground})`,
  onBackground = `var(--s-color-on-background, ${$color.lightOnBackground})`,
  outline = `var(--s-color-outline, ${$color.lightOutline})`,
  outlineVariant = `var(--s-color-outline-variant, ${$color.lightOutlineVariant})`,
  surface = `var(--s-color-surface, ${$color.lightSurface})`,
  onSurface = `var(--s-color-on-surface, ${$color.lightOnSurface})`,
  surfaceVariant = `var(--s-color-surface-variant, ${$color.lightSurfaceVariant})`,
  onSurfaceVariant = `var(--s-color-on-surface-variant, ${$color.lightOnSurfaceVariant})`,
  inverseSurface = `var(--s-color-inverse-surface, ${$color.lightInverseSurface})`,
  inverseOnSurface = `var(--s-color-inverse-on-surface, ${$color.lightInverseOnSurface})`,
  inversePrimary = `var(--s-color-inverse-primary, ${$color.lightInversePrimary})`,
  surfaceContainerLowest = `var(--s-color-surface-container-lowest, ${$color.lightSurfaceContainerLowest})`,
  surfaceContainerLow = `var(--s-color-surface-container-low, ${$color.lightSurfaceContainerLow})`,
  surfaceContainer = `var(--s-color-surface-container, ${$color.lightSurfaceContainer})`,
  surfaceContainerHigh = `var(--s-color-surface-container-high, ${$color.lightSurfaceContainerHigh})`,
  surfaceContainerHighest = `var(--s-color-surface-container-highest, ${$color.lightSurfaceContainerHighest})`,
  success = `var(--s-color-success, ${$color.lightSuccess})`,
  onSuccess = `var(--s-color-on-success, ${$color.lightOnSuccess})`,
  successContainer = `var(--s-color-success-container, ${$color.lightSuccessContainer})`,
  onSuccessContainer = `var(--s-color-on-success-container, ${$color.lightOnSuccessContainer})`,
  warning = `var(--s-color-warning, ${$color.lightWarning})`,
  onWarning = `var(--s-color-on-warning, ${$color.lightOnWarning})`,
  warningContainer = `var(--s-color-warning-container, ${$color.lightWarningContainer})`,
  onWarningContainer = `var(--s-color-on-warning-container, ${$color.lightOnWarningContainer})`,
}

export const enum $elevation {
  level1 = '0 1px 2px 0 rgb(0 0 0 / 20%), 0 1px 3px 1px rgb(0 0 0 / 10%)',
  level2 = '0 1px 2px 0 rgb(0 0 0 / 20%), 0 2px 6px 2px rgb(0 0 0 / 10%)',
  level3 = '0 1px 3px 0 rgb(0 0 0 / 20%), 0 4px 8px 3px rgb(0 0 0 / 10%)',
  level4 = '0 2px 3px 0 rgb(0 0 0 / 20%), 0 6px 10px 4px rgb(0 0 0 / 10%)',
  level5 = '0 4px 4px 0 rgb(0 0 0 / 20%), 0 8px 12px 6px rgb(0 0 0 / 10%)',
}

export const enum elevation {
  level1 = `var(--s-elevation-level1, ${$elevation.level1})`,
  level2 = `var(--s-elevation-level2, ${$elevation.level2})`,
  level3 = `var(--s-elevation-level3, ${$elevation.level3})`,
  level4 = `var(--s-elevation-level4, ${$elevation.level4})`,
  level5 = `var(--s-elevation-level5, ${$elevation.level5})`,
}

export namespace $shape {
  export const enum corner {
    extraSmall = '4px',
    small = '8px',
    medium = '12px',
    large = '16px',
    largeIncreased = '20px',
    extraLarge = '28px',
    extraLargeIncreased = '32px',
    extraExtraLarge = '48px'
  }
}

export namespace shape {
  export const enum corner {
    extraSmall = `var(--s-shape-corner-extra-small, ${$shape.corner.extraSmall})`,
    small = `var(--s-shape-corner-small, ${$shape.corner.small})`,
    medium = `var(--s-shape-corner-medium, ${$shape.corner.medium})`,
    large = `var(--s-shape-corner-large, ${$shape.corner.large})`,
    largeIncreased = `var(--s-shape-corner-large-increased, ${$shape.corner.largeIncreased})`,
    extraLarge = `var(--s-shape-corner-extra-large, ${$shape.corner.extraLarge})`,
    extraLargeIncreased = `var(--s-shape-corner-extra-large-increased, ${$shape.corner.extraLargeIncreased})`,
    extraExtraLarge = `var(--s-shape-corner-extra-extra-large, ${$shape.corner.extraExtraLarge})`
  }
}

export namespace $motion {
  export const enum duration {
    short1 = '50ms',
    short2 = '100ms',
    short3 = '150ms',
    short4 = '200ms',
    medium1 = '250ms',
    medium2 = '300ms',
    medium3 = '350ms',
    medium4 = '400ms',
    long1 = '450ms',
    long2 = '500ms',
    long3 = '550ms',
    long4 = '600ms',
    extraLong1 = '700ms',
    extraLong2 = '800ms',
    extraLong3 = '900ms',
    extraLong4 = '1000ms',
  }
  export const enum easing {
    emphasized = 'cubic-bezier(0.2, 0, 0, 1.0)',
    emphasizedDecelerate = 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
    emphasizedAccelerate = 'cubic-bezier(0.3, 0, 0.8, 0.15)',
    standard = 'cubic-bezier(0.2, 0, 0, 1.0)',
    standardDecelerate = 'cubic-bezier(0, 0, 0, 1)',
    standardAccelerate = 'cubic-bezier(0.3, 0, 1, 1)'
  }
}

export namespace motion {
  export const enum duration {
    short1 = `var(--s-motion-duration-short1, ${$motion.duration.short1})`,
    short2 = `var(--s-motion-duration-short2, ${$motion.duration.short2})`,
    short3 = `var(--s-motion-duration-short3, ${$motion.duration.short3})`,
    short4 = `var(--s-motion-duration-short4, ${$motion.duration.short4})`,
    medium1 = `var(--s-motion-duration-medium1, ${$motion.duration.medium1})`,
    medium2 = `var(--s-motion-duration-medium2, ${$motion.duration.medium2})`,
    medium3 = `var(--s-motion-duration-medium3, ${$motion.duration.medium3})`,
    medium4 = `var(--s-motion-duration-medium4, ${$motion.duration.medium4})`,
    long1 = `var(--s-motion-duration-long1, ${$motion.duration.long1})`,
    long2 = `var(--s-motion-duration-long2, ${$motion.duration.long2})`,
    long3 = `var(--s-motion-duration-long3, ${$motion.duration.long3})`,
    long4 = `var(--s-motion-duration-long4, ${$motion.duration.long4})`,
    extraLong1 = `var(--s-motion-duration-extraLong1, ${$motion.duration.extraLong1})`,
    extraLong2 = `var(--s-motion-duration-extraLong2, ${$motion.duration.extraLong2})`,
    extraLong3 = `var(--s-motion-duration-extraLong3, ${$motion.duration.extraLong3})`,
    extraLong4 = `var(--s-motion-duration-extraLong4, ${$motion.duration.extraLong4})`,
  }
  export const enum easing {
    emphasized = `var(--s-motion-easing-emphasized, ${$motion.easing.emphasized})`,
    emphasizedDecelerate = `var(--s-motion-easing-emphasizedDecelerate, ${$motion.easing.emphasizedDecelerate})`,
    emphasizedAccelerate = `var(--s-motion-easing-emphasizedAccelerate, ${$motion.easing.emphasizedAccelerate})`,
    standard = `var(--s-motion-easing-standard, ${$motion.easing.standard})`,
    standardDecelerate = `var(--s-motion-easing-standardDecelerate, ${$motion.easing.standardDecelerate})`,
    standardAccelerate = `var(--s-motion-easing-standardAccelerate, ${$motion.easing.standardAccelerate})`,
  }
}